### ISSUE TITLE
can we add a convenience method to add the same BL for multiple features?

### ISSUE THREAD

**Issue by berndbischl** [schalkdaniel/compboost#241]

**Comment by schalkdaniel** [comment]
have a look at `boostSplines()` and `boostLinear()`

**Comment by schalkdaniel** [comment]
but this is for all features

**Comment by berndbischl** [comment]
i would rather have something like addBaseLearners(features)

**Comment by ja-thomas** [comment]
We had this at one point and decided against this for two reasons:

1) base-learners might take multiple features as inputs so `addBaseLearners()` would need a list of features, since
`addBaseLearners(c("V1", "V2"), ...)` would create a single base-learner with two features. Which is imo. really unintuitive behaviour and would yield a lot of confusion. 

2) You can still add multiple base-learners in a single line, either by a `for` loop or and `*apply`, which hopefully everybody should be able to do. 

I'm closing this, since @schalkdaniel and I already discussed that quite a bit, feel free to reopen if you want to discuss this further.

**Comment by berndbischl** [comment]
ok, fine, i saw that point before. if this becomes annoying later, we can still reopen
