### ISSUE TITLE
Why is there no Object for the registered factories?

### ISSUE THREAD

**Issue by ja-thomas** [schalkdaniel/compboost#64]
This is strange imo.

Why don't you use a clean object with methods to register factories?

Currently The factories have methods to register themselve in an object where you don't have a reference symbol, and standalone function to list and clear the registered Factories.

**Comment by schalkdaniel** [comment]
There are global functions `printRegisteredFactorys()` and `clearRegisteredFactorys()` which does that. The problem here is that the conversion from e.g. a S3 Baselearner class of R can't be casted to a C++`Baselearner class by giving the S3 class as parameter. Maybe there are other smarter solutions for that. But at the moment it seems to be the easiest way to create a global object (static member of compboost) which then can be accessed from functions and other C++ classes. But you are right its a bit odd.

**Comment by schalkdaniel** [comment]
Another option would be to let it global on the C++ side and create an R6 object which has these member functions and wraps the global functions.

**Comment by schalkdaniel** [comment]
Done in #73
